Added test for running posix compliance test suite on nfs-ganesha export
nfs-ganesha/ci-tests pull request #11
Opened 2017-06-20 10:17 UTC by aloganat

Signed-off-by: Arthy Loganathan <aloganat@redhat.com>

2017-06-20 12:09 UTC, nixpanic requested changes
Some changes would be good. In case you have a (manual) test run in the CentOS CI, could you point to the console log?

2017-06-20 12:09 UTC, nixpanic commented on posix_compliance/client.py
> +cmd = "yum -y install git gcc nfs-utils redhat-rpm-config python-devel krb5-devel perl-Test-Harness *libacl*"
This `*libacl*` looks weird, is libacl-devel not sufficient?

2017-06-20 12:09 UTC, nixpanic commented on posix_compliance/client.py
> +posix_home = "/root/ntfs-3g-pjd-fstest/"
You could set this variable further up, and use it all over the place instead of writing the full path at the previous tasks.

2017-06-20 12:09 UTC, nixpanic commented on posix_compliance/client.py
> +subprocess.call(cmd, shell=True)
If mounting fails, you should probably just exit with an error?

2017-06-20 12:09 UTC, nixpanic commented on posix_compliance/client.py
> +cmd = "rm -rf /root/ntfs-3g-pjd-fstest && git clone https://github.com/ffilz/ntfs-3g-pjd-fstest.git"
Maybe place the path for this git repo as a variable in the top of the script?
I know Zorro Lang (zlang@redhat.com) does some tests and corrections to the upstream project too. Is that different from the repository from Frank Filz?

2017-06-21 13:33 UTC, aloganat commented on posix_compliance/client.py
> +cmd = "rm -rf /root/ntfs-3g-pjd-fstest && git clone https://github.com/ffilz/ntfs-3g-pjd-fstest.git"
posix test suite in Frank Filz repository is more specific to nfs ganesha. He has modified some tests and code to be specific to nfs ganesha. So, I have cloned Frank's repository.

2017-06-21 13:44 UTC, ffilz commented on posix_compliance/client.py
> +cmd = "rm -rf /root/ntfs-3g-pjd-fstest && git clone https://github.com/ffilz/ntfs-3g-pjd-fstest.git"
I should push my pjdfstest repos to the nfs-ganesha github for more assured project posterity (not that my personal github is going anywhere)

2017-06-21 13:56 UTC, merged