build-fsal_gluster: add userspace-rcu-devel to packages to install
nfs-ganesha/ci-tests pull request #39
Opened 2018-11-13 16:11 UTC by jtlayton

Future versions of ganesha will require userspace RCU, which is
available via epel. Install the epel-release package first, and then
userspace-rcu-devel.

Signed-off-by: Jeff Layton <jlayton@kernel.org>

2018-11-13 17:07 UTC, dang approved these changes

2018-11-13 17:09 UTC, jtlayton commented
Note that I don't really have a way to test this before merging it, but it's fairly straightforward.

2018-11-14 03:50 UTC, thotz approved these changes

2018-11-14 08:38 UTC, nixpanic requested changes
This is probably not the right thing to do. userspace-rcu is also part of the repositories provided by centos-release-gluster and centos-release-ceph. Trying to install it from EPEL might get you a different version and cause conflicts.

2018-11-14 10:50 UTC, jtlayton commented
Thanks @nixpanic. I removed the installation of epel release, though I went ahead and left in the change to make the storage SIG repos installed with a single yum command.

2018-11-14 11:36 UTC, nixpanic approved these changes
Thanks, looks good to me now too :)

2018-11-14 11:38 UTC, thotz approved these changes

2018-11-14 13:58 UTC, merged